services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: -Xmx2G -Xms2G
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_MESSAGE_MAX_BYTES: 1500000000          # 1.5GB
      KAFKA_REPLICA_FETCH_MAX_BYTES: 1500000000    # 1.5GB
    depends_on:
      - zookeeper
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092"]
      interval: 10s
      retries: 5



  python-client:
    build: .
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
